project/__init__.py
from flask import Flask, config
from project.main.routes import main
from project.admin.routes import admin
from flask_mysqldb import MySQL

app = Flask(__name__)

app.secret_key = "123456"
app.config['MYSQL_HOST']= 'localhost'
app.config['MYSQL_USER']= 'root'
app.config['MYSQL_PASSWORD']= ''
app.config['MYSQL_DB']= 'flaskapp'

db = MySQL()
db.init_app(app)


# registering blueprint
app.register_blueprint(main, url_prefix='/')
app.register_blueprint(admin, url_prefix='/admin')

project/admin/routes.py
from flask import Blueprint

admin = Blueprint('admin',__name__)

@admin.route('/')
def home():
    return 'admin home page'

project/main/routes.py
from flask import Blueprint
from flask.helpers import flash, url_for
from flask.templating import render_template
from flask import request,redirect,jsonify
from flask.wrappers import Response

main = Blueprint('main',__name__)


@main.route('/')
def home():

    # fetch all user from the database
    from project import db
    cur = db.connection.cursor()
    exec_query = cur.execute("SELECT * FROM user")
    if exec_query >0:

        results = cur.fetchall()
        return render_template('index.html',results=results)

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/form' ,methods=['GET','POST'])
def data():
    if request.method == 'POST':

        name = request.form['name']
        email= request.form['email']

        from project import db
        cur = db.connection.cursor()
        cur.execute("INSERT INTO user (name,email) VALUES(%s,%s)",(name,email))
        cur.connection.commit()
        cur.close()
        flash('User sucessfully inserted')
        return redirect(url_for('main.home'))

    return render_template('form.html')

@main.route('/edit/<id>',methods=['GET','POST'])
def edit(id):
    from project import db

    if request.method=='POST':

        name = request.form['name']
        email = request.form['email']
        data = (name,email)

        cur = db.connection.cursor()
        results = cur.execute("UPDATE user SET name=%s, email=%s WHERE user_id=%s",(name,email,id))
        if results:
            cur.connection.commit()
            cur.close()
            flash('User Data Successfully updated')
            return redirect(url_for('main.home'))

    cur = db.connection.cursor()
    cur.execute(f'SELECT * FROM user Where user_id={id}')
    results = cur.fetchone()
    
    return render_template('edit.html',results=results)

@main.route('/delete/<id>')
def delete(id):

    from project import db
    try:

        cur = db.connection.cursor()
        result = cur.execute("DELETE FROM user WHERE user_id=%s",(id))
        if result:
            cur.connection.commit()
            cur.close()
            flash('User has successfully been deleted')
            return redirect(url_for('main.home'))
    except ProgrammingError:
        return redirect(url_for('main.home'))

    



    

project/templates/about.html
{% extends 'base.html'%}

{% block content%}
<div class="container">
 <h2>about us page</h2>
</div>
{% endblock%}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask App</title>
    <link rel="stylesheet"  href="{{ url_for('static', filename='css/assets/bootstrap4/css/bootstrap.min.css') }}">
    <script src="{{url_for('static',filename='js/index.js')}}"></script>
    
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

project/templates/edit.html
{% extends 'base.html'%}

{% block content%}
<div class="container">
    <form method="POST" action="">
        <div class="form-group">
          <label for="exampleInputEmail1">FullName</label>
          <input type="text" class="form-control" id="exampleInputEmail1"
            name="name" placeholder="your name" value="{{results[1]}}">
           </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Email Address</label>
          <input type="email" class="form-control" id="exampleInputPassword1"
          name="email" placeholder="email" value="{{results[2]}}">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
{% endblock%}

project/templates/form.html
{% extends 'base.html'%}

{% block content%}
<div class="container">
  {% for message in get_flashed_messages():%}
   {% if message:%}
  <div class="alert alert-primary" role="alert">
    {{message}}
  </div>
  {% endif%}
  {% endfor%}
    <form method="POST" action="">
        <div class="form-group">
          <label for="exampleInputEmail1">FullName</label>
          <input type="text" class="form-control" id="exampleInputEmail1"
            name="name"aria-describedby="emailHelp" placeholder="your name">
           </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Email Address</label>
          <input type="email" class="form-control" id="exampleInputPassword1"
          name="email" placeholder="email">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
{% endblock%}

project/templates/index.html
{% extends 'base.html'%}

{%  block content %}
<style>
    #myh{
        color: red;
    }
   </style>
   
<div class="container">
    <br>
    {% for message in get_flashed_messages():%}
   {% if message:%}
  <div class="alert alert-primary" role="alert">
    {{message}}
  </div>
  {% endif%}
  {% endfor%}

  <br>
    <a href="{{url_for('main.data')}}" class="btn btn-secondary">Add User</a>
    <br>
    <br>
    <table class="table table-striped table-dark">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Number</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Edit detail</th>
            <th scope="col">Delete User</th>
          </tr>
        </thead>
        <tbody>
          {% for result in results:%}
          <tr>
          <td>{{result[0]}}</td>
          <td>{{result[1]}}</td>
          <td>{{result[2]}}</td>
          <td><a href="{{url_for('main.edit',id=result[0])}}" class="btn btn-primary d-flex justify-content-center">Edit</a></td>
          <td><a href="{{url_for('main.delete',id=result[0])}}" class="btn btn-danger d-flex justify-content-center">Delete</a></td>
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
</div>

{% endblock %}